paulgazz/kmax

- kextractors/kextractor-next-20200430/kextractor_extension.c
Ref: Issue #15 
It seems like `kextract_extension.c::kextract()` fails due to some version differences with the Python/C API.
The changes solves the issue for me but I didn't put further thought on whether this is the best way to solve this issue.
> kextractors: fix python->c arg passing

- kmax/klocalizer
Python sets are not ordered by default. Although the set equality is
satisfied in different runs, traversing the set in different orders leads
klocalizer to produce different outputs in different runs. Although these
outputs are equivalent in terms of successfully building the compilation
units in question, the difference in config files prevents reproducibility.
Traverse over ordered set instead to fix the issue.
> kmax: klocalizer: fix the bug preventing reproducibility

- kmax/klocalizer
The existing `--constraints-file` CLarg isn't useful in providing more
complex constraints such as conjunctions or disjunctions.
Add `--constraints-file-smt2` option to allow inputting smt2 constraints
file.
> klocalizer: allow inputting smt2 constraints file

- kmax/kclause
Add `--normal-dependencies-only` and `--reverse-dependencies-only` flags
to allow printing normal and reverse dependencies invididually per Kconfig
symbol.
> kclause: allow printing normal and reverse deps individually

- kmax/klocalizer
- scripts/kclause_to_composite.py
Currently, kclause files are dictionaries, which are needed to be parsed
by klocalizer on each run such that each clause in the dictionary is
accumulated to a constraints list. This process has a great share on
the overall running time the kclause by almost doubling it.
Create a new kclause format, i.e., composite kclause, which takes away
the need for traversing a dictionary, and instead stores the composite
clauses already accumuluated in a list.
kmax/klocalizer now takes --use-composite-kclause-formulas-files flag,
which tells klocalizer to interpret the kclause formulas file in composite
format.
scripts/kclause_to_composite.py can be used to convert kclause files into
composite kclause files. The functionality of this script can be later
embedded into the formula extractor/generator …
> kclause: introduce composite kclause formulas file format to boost performance

- kextractors/kextractor-next-20200430/kextractor.c
- kmax/kclause
- tests/kclause_tests/emptyChoice
- tests/kclause_tests/emptyChoice.extract
- tests/kclause_tests/emptyChoice.pickle
Choice and choice values are selectable only when both their depends on and visibility constraints are satisfied.
Regarding this, the following changes are made:
- Condition for choice now uses correct visibility condition and does not use dir_dep and rev_dep.
- Kclause uses visibility of choice values (which has depends on constraint conjuncted by kconfig) to generate choice clauses.
In addition, there is a small optimization to avoid generating redundant clauses for the choice mutex.
> Change choice handling to consider both depends on and visibility constraint

- kmax/klocalizer
- tests/klocalizer_tests/assets/unmetdd_constraints_for_GENERIC_PINCONF_by_PINCTRL_RT2880.smt2
- tests/klocalizer_tests/assets/unmetdd_constraints_for_GPIOLIB_IRQCHIP_by_PINCTRL_BCM2835.smt2
- tests/klocalizer_tests/assets/unmetdd_constraints_for_GRO_CELLS_by_MACSEC.smt2
- tests/klocalizer_tests/testunmetfree.sh
Unmet direct dependency for a config C can be avoided by using
implication(C, dir_dep_C) constraint. Adding such constraint for all
symbols would force the output config to be unmet direct dependency free.
The new option --force-unmet-free achieves by creating another kclause
formulas file, i.e. kclause direct dependency formulas, and using this
to add such constraints.
With --allow-unmet-for, one can add exceptions to --force-unmet-free by
listing for which symbols to not add such constraint.
The newly added tests, i.e. tests/testunmetfree.sh, demonstrates and tests
the usage of the newly added options.
Finally, some refactoring is done in klocalizer for the sake of
readability.
> klocalizer: add --force-unmet-free and --allow-unmet-for options

- kmax/kclause
- tests/kclause_tests/unmetChain1
- tests/kclause_tests/unmetChain1.extract
- tests/kclause_tests/unmetChain1.pickle
- tests/kclause_tests/unmetChain2
- tests/kclause_tests/unmetChain2.extract
- tests/kclause_tests/unmetChain2.pickle
- tests/kclause_tests/unmetChain3
- tests/kclause_tests/unmetChain3.extract
- tests/kclause_tests/unmetChain3.pickle
- tests/kclause_tests/unmetChain4
- tests/kclause_tests/unmetChain4.extract
- tests/kclause_tests/unmetChain4.pickle
Unmet dependency may break the chain of select statements over config options, 
as select statement of a config options is in effect only when the option's depends on 
constraint is met, regardless of whether the option is being selected by other option's
select constraints.
Kextract handles this correctly by conjoining the conditions of select and depends on,
but kclause was removing the condition from depends on to reduce the length of the
formula.  This is disabled for the correct behavior of select.
> Fixed unmet direct dependency to break the chain of selects

- kmax/kismet
- kmax/klocalizer.py
* **restricting to symbols:** allows to analyze only for the listed set of selectees/selectors
* **fix CONFIG_BROKEN:** disable CONFIG_BROKEN by default to avoid trivial false positives due to having CONFIG_BROKEN enabled
> kismet: allow restricting to symbols, fix CONFIG_BROKEN issue

- kmax/kclause
orphaned nonvisibles, i.e., non-prompt boolean options with no default values
and selected nowhere, cannot be enabled. make this explicit by unsetting such
options in kclause formulas.
> kclause: unset orphaned nonvisibles

- kmax/about.py
- kmax/arch.py
- kmax/klocalizer
Introduce --kextract-version flag to klocalizer to let user manually
set up the kextract module version used for kextract file generation.
If kextract-version is unset, have Arch automatically detect and use
the latest module version suitable for the kernel version.
> klocalizer/arch: introduce --kextract-version flag

- kmax/kclause
- kmax/klocalizer.py
This should fix the issue where nonvisible config variables did not have default values set in generated .config files, causing additional effort for klocalizer users.
Properly handling default values for nonbooleans is combinatorially explosive, requiring over 16gb of ram for linux 5.11. This is because adding the default value expressions for all corresponding ghost booleans to the z3 solver requires making all of the expressions mutually-exclusive to each other. A few config options have many complex expressions, making this a problem.
More testing is needed to ensure that there are no regressions, and that this truly does resolve all instances of this issue.
> Klocalizer: write dummy values for visible nonboolean config options

- kmax/arch.py
While Arch can automatically detect the kextract module version
suitable for the Linux kernel version, this can possibly fail for
Linux trees that are not yet releases, thus, have inaccurate version
assignments.
To have klocalizer/Arch avoid failing in such cases, try all available
kextract module versions until kextract succeeds if detected one fails.
If module version is explicitly set, only the given version is tried.
> Arch: Try available kextract versions if detected version fails

- tests/py_unittests/run_tests.sh
The tests would fail if run_tests.sh is run outside the directory
of the script. Fix this by cd'ing into script dir before running.
Also, logging is improved.
> tests: py_unittests: fix test runner

- kmax/klocalizer
- kmax/klocalizer.py
Firstly, the default directory holding formulas is now Linux version specific.  For example, the kclause formulas will be at .kmax/next-20210512/kclause
This is useful to avoid using the wrong formula cache when checking out another version of Linux in a git repository.  klocalizer will first check the version with git describe or make kernelversion if it is not a git clone.  The consequence is that all formula caches will remain on disk until manually deleted by the user.
Since the tool detects the version, it can tell whether the formulas are already cached.  If not, it will try to find prebuilt formulas at https://configtools.org/klocalizer/cache/VERSION.  If the user has a folder for that version, however, i.e., if they already generated some of the formulas, then no download will …
> Automatically d/l cached formulas; version-specific .kmax folders

- kmax/klocalizer
This option will write constraints to a given file in DIMACS format instead of generating a .config file.
This can be combined with other options, e.g., `-a` to specify the architecture and/or `--constraints-file-smt2 to conjoin additional constraints in the SMT-LIBv2 format.
Fixes #54
> Add the --save-dimacs options to write constraints to a DIMACS file

- kmax/klocalizer
`--report-all` fails with `--sample 0` or without sample flag although it should not. Fix this.
Fixes #84
> klocalizer: fix using --sample 0 with --report-all

- kmax/klocalizer.py
For replicability, use fixed output order.
> klocalizer: ConditionalBlock.get_deepest_block: use fixed output order

- kmax/klocalizer.py
SuperC outputs config options as |(defined CONFIG_OPTION)|. kclause
treats config options to be boolean, and uses CONFIG_OPTION
directly as the variable to define whether the config is defined,
without the "defined" keyword.
For compatibility, transform SuperC format into kclause format when
parsing ConditionalBlocks from string.
This will have no affect if the string is already in kclause format.
> klocalizer: ConditionalBlock: fix parsing PC from SuperC output

- kmax/klocalizer.py
Use SourcelinePcResult enum to return status from sourceline pc
computing method: Klocalizer.get_sourceline_pc_linux_file().
Dump stdout/err of make/superc if they fail.
> klocalizer: sourceline_pc: handle and report errors

- kmax/klocalizer.py
- kmax/vcommon.py
Add time measuring and timeout capabilities to `common.run()`.
For `Klocalizer.get_sourceline_pc_linux_file()`:
* Measure and report the time spent for external processes, including:
* Architecture detection (or SAT check) by klocalizer
* e.g.: `INFO: TIME: Time elapsed(sec) for architecture search: 3.58`
* Config creation by klocalizer
* e.g.: `INFO: TIME: Time elapsed(sec) for creating the config file: 7.79`
* make olddefconfig
* e.g.: `INFO: TIME: Time elapsed(sec) for running make olddefconfig: 3.51`
* make
* e.g.: `INFO: TIME: Time elapsed(sec) for running make: 8.34`
* SuperC config creation
* e.g.: `INFO: TIME: Time elapsed(sec) for SuperC config generation: 1.69`
* SuperC sourceline pc computation
* e.g.: `INFO: TIME: Time elapsed(sec) for running SuperC: 1.20`
* Take make_timeout …
> klocalizer: sourceline_pc: add time measuring and timeout

- kmax/klocalizer.py
Usually, compiling a source file src/file.c requires passing src/file.o
to make as target. However, there are exceptions to this such as needing
to pass the parent directory.
To account for such exceptions, introduce `build_target` argument.
> sourceline_pc: use build targets

- kmax/klocalizer
Let user be able to disable downloading formulas and instead generate
formulas by using the --disable-downloading-formulas flag.
This is useful when:
* User wants a freshly generated formulas since the kernel version is
not an indicator of the Kconfig specs (e.g., user manually changed the
Kconfig specs, user is experimenting changes to some modules etc.)
* User does not want to use the network (slow internet, does not trust
downloaded content etc.)
> klocalizer: add --disable-downloading-formulas flag

- kmax/superc.py
SuperC linux script searches the Linux config file in LINUX_KSRC/.config
implicity (it runs make, which uses the kconfig file at this path by
default).  We knew that before and had an assertion in python module
that the .config file exists at this path.
On the other hand, SuperC python module keeps the config file elsewhere
for diagnostic purposes.
Make a copy of this config file at LINUX_KSRC/.config before running
superc_linux.sh for superc config creation.
(This commit also adds an unrelated yet useful assertion.)
Fixes #127
> fix: superc config gen: copy .config for superc_linux.sh to find

- kmax/klocalizer
--formulas used to point to the directory, where the formula cache is
contained without accounting for different build system versions based
on cache.  In other words, it included kclause, kmax files directly.
Now we use subdirectories inside formulas directory named with build system
hash ids.  Let --formulas point to this top directory that contains one
directory per unique build system.
How to test:
```
cd linux-ksrc/ # change as needed
rm -rf .kmax
klocalizer # this should create .kmax/
ls .kmax/ # should contain a subdir with 12-char hashcode name
mv .kmax/ my_formulas/
klocalizer --formulas my_formulas/  # should reuse my_formulas and create a .config
klocalizer --formulas non_existing_dir/ # should create non_existing_dir/
ls non_existing_dir/ # should contain a subdir with 12-char …
```
> klocalizer: fix formulas arg to account for cache subdirs

- docs/advanced.md
- docs/overview.md
- kmax/koverage
- kmax/patch.py
- setup.py
`koverage` is a tool that checks build coverage of a Linux configuration
file for given set of (file:line)s.
See the documentation changes for how to use koverage.
TODOs:
* Method: for each commit, checkout to the commit.  Create patch file.  Create allyesconfig.  Check coverage.  Summarize results using additional scripts and compare to krepair results.
> introduce koverage: build coverage checking tool

- kmax/arch.py
- kmax/kismet
These changes fix small issues in https://github.com/paulgazz/kmax/pull/148
[arch: get kextract module versions from kextractcommon](https://github.com/paulgazz/kmax/commit/60bdf1f05db3e2d900dacb15cb3d4868815c954f)
[kismet: fix newlines in new log messages](https://github.com/paulgazz/kmax/commit/cf620ce730072f54260755d0d6e30718549fd0ce)
> let arch get kextract module versions from kextractcommon, fix newlines in kismet log messages

- kmax/klocalizer
Local methods unit2srcfile() and srcfile2unit() is used to change
extensions between .c and .o.  In some cases, they are called even if
the extension is already the target one (e.g., unit2srcfile() is called
while extension is already .c).
Change the assertions inside those methods to accept this, so that
they can be used with more flexibility, without needing to keep track of
what the current extension was.
Fixes https://github.com/paulgazz/kmax/issues/156
> klocalizer: relax unit/srcfile extension check

- MANIFEST.in
- kextractors/kextractor-3.19/kextractor.c
- kextractors/kextractor-4.12.8/kextractor.c
- kmax/kismet
- kmax/resources/kismet_udd_printer_extension.h
- kmax/resources/kismet_verification_patch.diff
- kmax/udd_warning_parser.py
- setup.py
This does the following changes to have kismet run for older linux kernel versions:
* backport kextract fixes from newer versions to older kextract versions (3.19 and 4.12.8)
* let kismet validate with older kbuild versions by parsing dependency warning messages in old format
Fixes https://github.com/paulgazz/kmax/issues/163
Fixes #167
> adapt kismet to run for older linux kernel versions

- MANIFEST.in
- kextractors/kextractor-3.19/kextractor.c
- kextractors/kextractor-4.12.8/kextractor.c
- kmax/kismet
- kmax/resources/kismet_udd_printer_extension.h
- kmax/resources/kismet_verification_patch.diff
- kmax/udd_warning_parser.py
- setup.py
This uncomments the output of "select ..." lines in the kextract output, which is used by kismet to get the list of select constructs.  It was originally commented out in favor of "rev_dep ..." lines for kclause, which no longer needs the selects lines.
Fixes #161
Fixes #159
> Fix outputting select constructs for older kextractor versions

- kmax/arch.py
- kmax/kextractlinux
Tell the user and raise an ArchitectureUnavailableError exception if the requested architecture is not available in the selected version of the Linux kernel.
Fixes #160
> Check whether the architecture exists when running kextract

- kmax/arch.py
- kmax/kismet
Catch exceptions of type `Arch.CantOpenKconfigFiles` and write a specific
error message to inform the issue with the input Kconfig specifications.
For example, when you run the following in a Linux git copy:
```
git checkout 012e3ca3cb4d7f
kismet -a x86_64
```
kismet will output (tail of the kismet logs) and terminate:
```
ERROR: Can't open Kconfig files:
drivers/media/platform/Kconfig:69: can't open file "drivers/media/platform/am437x/Kconfig"
```
Fixes https://github.com/paulgazz/kmax/issues/164
> kismet: raise specific error when Kconfig files can't be opened

- kmax/kismet
kismet used to print info/warning/error on stderr. To distinguish, print
info on stdout and keep warning/error on stderr.
> kismet: print INFO logs on stdout

- docs/advanced.md
- kmax/koverage
**koverage: add command line options to control timeout durations (https://github.com/paulgazz/kmax/commit/ee78d1b7bacb2ae5e3502e3de4e4c2ae75e38417)**
Timeout durations for running make commands were fixed. Introduce new
command line options to control the timeout durations, which are:
--timeout-make-olddefconfig, --timeout-make-dir, --timeout-make-unit
**koverage: use explicit inclusion values for timeouts (https://github.com/paulgazz/kmax/commit/cb0dea436445b4f685bf545124081b8e52b9b640)**
When make timed out, koverage used "FILE_EXCLUDED" as the inclusion
value for the target lines.  However, timeouts do not mean the file/line
is excluded from compilation. Instead use new values, which are
TIMEOUT_MAKE_OLDDEFCONFIG and TIMEOUT_MAKE.
> koverage: add timeout durations options, use explicit values in results when timeouts happen

- kmax/klocalizer
- kmax/klocalizer.py
Previously, get_config_from_model would populate any enabled nonbool options by setting them to defaults.  This breaks builds sometimes, e.g., when repairing defconfig to cover the patch
c07ba878ca199a6089cdb323bf526adbeeb4201f, because
`CONFIG_PHYSICAL_START` is set to 0, which the linker complains about. With this change, `CONFIG_PHYSICAL_START` is set to 0x1000000 from the input defconfig.  This is an example of it in action:
```
git checkout c07ba878ca199a6089cdb323bf526adbeeb4201f
git show > c07ba878ca199a6089cdb323bf526adbeeb4201f.patch
make defconfig; cp .config defconfig
klocalizer --repair defconfig --include-mutex c07ba878ca199a6089cdb323bf526adbeeb4201f.patch -a x86_64 --no-nonbool-preservation
koverage --check-patch c07ba878ca199a6089cdb323bf526adbeeb4201f.patch --arch x86_64 …
```
> Use the repaired config to populate nonbool options

- kmax/arch.py
- kmax/klocalizer
klocalizer uses a fixed-order list of architectures to try to localize when the architecture is not provided by the user.  Optimize this ordering by looking for files given to include-mutex that are in the arch/ directories by putting those architectures first in the list.
Example:
```
git checkout 35d02493dba1ae6386fac07072908717affc3ff8
git show > patch.diffa
make defconfig
cp .config defconfig
klocalizer --repair defconfig --include-mutex patch.diff
koverage --config patch.diff --check-patch patch.diff -o coverage.json --arch s390
```
> Prioritize architectures of compilation units in arch/ directories

- kmax/arch.py
Without this, klocalizer will not check loongarch's kconfig for a possible repair.
This also reorders the arch slightly to put arm before i386.
Fixes #193
> Added the loongarch architecture

- kmax/klocalizer
- kmax/klocalizer.py
- kmax/superc.py
Previously, the use of the nonbools from the repaired config were only used for the --include-mutex algoritm.  Without this flag, a different algorithm is used (which assumes no mutual exclusion in the constraints and can therefore more be unsat).
Now, the nonbool preservation has also been added to that algorithm.
An example:
```
git checkout 0a434e0a2c9f4395e4560aac22677ef25ab4afd9
git show > patch.diff
cp .config defconfig
```
After this fix, the following will build successfully:
```
klocalizer -a arc --repair defconfig --include lib/decompress_unxz.o
make.cross ARCH=arc olddefconfig; make.cross ARCH=arc clean lib/decompress_unxz.o
```
Prior behavior is preserved by using the existing
`--no-nonbool-preservation` flag, which yields a broken build due to invalid non-boolean option …
> Support nonbool preservation when collecting sourceline presence conditions and when repairing without mutual exclusion

- README.md
This also puts the superc classpath before the original classpath to avoid shadowing of java dependencies.
Fixes #191
> Add COMPILER_INSTALL_PATH for make.cross

- kmax/superc.py
You can trigger this bug before the fix with the following use of krepair:
commit=1a90bfd220201fbe050dfc15deaac20ca5f15638; git checkout -f $commit; git show > patch.diff; make defconfig; cp .config defconfig; klocalizer -v -a arc --repair defconfig --include-mutex patch.dif
Fixes #202
> Fix the check for a broken build when getting SuperC conditions

- kmax/klocalizer
Currently, if the Linux version is missing an architecture, e.g., c6x, klocalizer will halt with an error.  This fix updates the algorithm to check the exceptions to formula generation and continue on the search.
> Continue search for config even when an arch/ dir is missing

- kmax/klocalizer.py
Previously, klocalizer would use fixed non-Boolean values, e.g., 0 for numbers, and a prior update (#184) added support for reusing the values from an input configuration when using the --repair option.  In this update, if there is no setting from the input configuration file, klocalizer will look at the default values in the Kconfig file (via kextract), and use one of them for the value, falling back to the fixed one if that isn't available.  Currently it picks the last default value, since Kconfig allows for multiple defaults.  But in the future, it would be best to use constraint solving to pick the right default, since each default is associated with a condition when there are multiple.
> Use Kconfig default values when non-Boolean options get enabled

- kmax/koverage
koverage will not overwrite a scratch directory by default.  This adds an option (-f/--force-overwrite-scratch-dir) to remove the directory first if it already exists.
Fixes #210
> Add an option to force-overwrite koverage's scratch-dir

- kmax/klocalizer
Previously, when generating a configuration file given constraints on config options, files, and/or lines, an assertion would trigger because there is no configuration file given as input to repair. klocalizer should be able to generate a config file according to constraints without an input file as was prior behavior.  This removes the asserts allow configuration file generation to proceed.
Fixes #223
> Remove assertions that require a config to repair

- kmax/klocalizer.py
A new feature from v4.5 uses Kconfig default values for nonbools.  It assumed the values are quoted literals.  But nonbool defaults may also be other configuration options.  This fix checks that only quoted literals are used as nonbool values.
Fixes #239
> Fix bug in .config file generation that uses invalid nonbool value

- setup.py
An error of dependency issue between networkx and dd was thrown during installation:
$ python3 setup.py install
...
error: networkx 2.2 is installed but networkx>=2.4 is required by {'dd'}
dd released a new version 0.6.0 recently which removed the support for old versions of python, and the networkx requirement was also updated to 2.4 accordingly.
Please refer to the following commit of dd repository:
https://github.com/tulip-control/dd
08ce37263ec8 ("REL: require Python >= 3.8")
- REL: require `networkx >= 2.4` in `tests_require`,
because this is the earliest `networkx` version that
explicitly lists Python 3.8 in its Trove classifiers.
Since networkx is set to 2.2 to work on python2, here we can also set dd to an earlier release 0.5.7 to solve the dependency issue.
Reported-by: kernel …
> setup.py: explicitly set dd version to 0.5.7

- kmax/alg.py
```
/kmax/alg.py", line 1099, in extract
makefile = open(makefile, "rU")
^^^^^^^^^^^^^^^^^^^^
ValueError: invalid mode: 'rU'
```
> open mode "rU" throws an error in python 3.11; changed to "r"

- docs/bugs_found.md
Currently, the link to kismet bugs looks at the whole lkml, which can include other things called kismet or other messages.
Switch to oe-kbuild-all (as used by Philip at Intel)
> Update the mailing to search for kismet bugs in the docs

- kmax/kismet
- setup.py
This parallelizes kismet, the unmet dependency checker for Kconfig.  kismet works by creating verification conditions for each Kconfig selector and selectee, then uses z3 to check whether the condition allows for an unmet dependency.  The checks for each selector/selectee pair are independent, so they can run in parallel.  There are three checkers, syntactic, optimized, and precise.  Syntactic is so fast, that parallelizing is negligible compared to the other phases.  The optimized and precise checkers have been parallelized.
Previously, the checker code ran a big loop over all pairs of selectors and selectees (and a visibility condition, making it a triple loop).  This merge factors out the code to check each triple and uses python's multiprocessing library to parallelize the checks. …
> Parallelize kismet

- pymake/process.py
> Remove the imp dependency from pymake, which isn't even used

- kmax/klocalizer.py
This checks whether the option is tristate or bool first, before setting it to 'n' via a "# CONFIG_A is not set" line.
Fixes #269
> Fix a bug where klocalizer sets nonbools to 'n'

- kmax/arch.py
- kmax/kclause
- kmax/kismet
The new kclause support for modeling tests of specific tristate values works for the default kclause output.  But kismet uses two custom formula extractions (normal-dependencies and selects) that have not yet been updated to use the tristate values.  Since the tristate value modeling requires some global support, handling this for kismet's formula extractions will require additional effort.
This additionally adds an option to disable kclause's new tristate modeling, which is used by kismet.  It also moves kismet's formula folder to .kismet instead of .kmax.
> Kismet separate formula creation

- kmax/superc.py
As demonstrated in #277, kmax's SuperC-less tokenizer (`kmax/superc.py`) currently doesn't account for conditional directives without a space between the directive and the parenthesis, such as:
```
netif_stop_queue(dev);
#if(NUM_XMIT_BUFFS > 1)  //affected line
if(test_and_set_bit(0,(void *) &p->lock)) {
```
The issue lies in how the `get_tokens()` method tokenizes parts of the C code. Currently, the function is a bit simplistic in its logic for separating different parts of comments or directives from one another, in particular, it relies heavily on spaces to start a new token:
```
for c in s:
if c == ' ' or c == '\t':
if buf != "":
token_list.append((buf, line_num))
buf = ""
else:
```
That being said, it lacks a system for determining the impact of a starter parenthesis on a directive, …
> Add fix for interpreting directives without spaces

- kmax/common.py
This PR changes the indentation in `common.py`'s `FileChangeType` class from tabs to spaces.
> Adjust spacing/indentation for FileChangeType class

- kmax/patch.py
At times, the Linux kernel can encounter modifications to file types that will change their `SourceFileType` from `SOURCE` to `OTHER`, as seen in #256:
```
diff --git a/arch/s390/crypto/crc32be-vx.S b/arch/s390/crypto/crc32be-vx.c
similarity index 56%
rename from arch/s390/crypto/crc32be-vx.S
rename to arch/s390/crypto/crc32be-vx.c
```
This change to the code should account for those modifications, provided that the `FileChangeType` is already set as `MOVED_MODIFIED`. 
* At this time, the code is _**lightly tested.**_ The change allows the code to get further in the set of commits provided in #256 by addressing the AssertionError.
* Without the fix from #275, `kmax` will run into the same error detailed in #274. 
* ~~That being said, it's worth noting that applying the commits brought up …
> Allow file type changes if file is classified as MOVED_MODIFIED

- kmax/common.py
- kmax/patch.py
Previously, kmax's `FileChangeType` class did not account for file permission changes in diff files, which caused an `AssertionError` to appear in those cases. This pull request simply adds another type, `PERMISSION_CHANGED`. Logic elsewhere isn't changed in the code.
- The change assumes that permission changes "aren't interesting" and aren't worth setting configuration options for.
- I changed the `FileChangeType` class's tabs to spaces to align with modern Python code styling.
- The pull request has only been tested on the steps under #274. It is not tested any further, so feel free to request changes.
> Handle changed file permissions
